#!/usr/bin/env sh

trap shutdown INT

# Start fireworq in the background
fireworq &
lpid=$!

# Wait for fireworq to be available
while ! nc -z localhost && kill -0 $lpid > /dev/null 2>&1; do
  echo "Waiting for fireworq"
  sleep 2s
done

if kill -0 $lpid > /dev/null 2>&1; then
  # Let fireworq wrap up any remaining setup
  # (setup continues after the server is available)
  sleep 5s

  # Run queue init
  setup-queues
else
  echo "Fireworq crashed, shutting down"
  exit 1
fi

function shutdown() {
  echo "Caught shutdown signal"
  kill -s SIGINT $lpid
}