#!/usr/bin/env sh

trap shutdown INT

# Start fireworq in the background
fireworq &
lpid=$!

address="${FIREWORQ_BIND:-localhost:8080}"
ncTarget=$(echo $address | sed 's/\[::\]/localhost/;s/:/ /')

echo "Checking fireworq status"
# Wait for fireworq to be available
while ! nc -z $ncTarget; do
  if ! kill -0 $lpid > /dev/null 2>&1; then
    echo "Fireworq crashed, shutting down"
    exit 1
  fi
  echo "Waiting for fireworq..."
  sleep 2s
done

if kill -0 $lpid > /dev/null 2>&1; then
  # Let fireworq wrap up any remaining setup
  # (setup continues after the server is available)
  sleep 5s

  # Run queue init
  setup-queues -q $address

  wait $lpid
else
  echo "Fireworq crashed, shutting down"
  exit 1
fi

function shutdown() {
  echo "Caught shutdown signal"
  kill -s SIGINT $lpid
}